//
// Created by Hamza El-Kebir on 4/18/21.
//

#ifndef LODESTAR_LODESTARERRORS_HPP
#define LODESTAR_LODESTARERRORS_HPP

enum LODESTAR_ERROR {
    ERROR_NONE = 0,
    ERROR_IMPROPER_TRANSFER_FUNC
};

#endif //LODESTAR_LODESTARERRORS_HPP
