/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_NPB_CUSTOMTYPEENUM_PB_H_INCLUDED
#define PB_NPB_CUSTOMTYPEENUM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _npb_TypeEnum { 
    npb_None_t = 0 
} npb_TypeEnum;

/* Helper constants for enums */
#define _npb_TypeEnum_MIN npb_None_t
#define _npb_TypeEnum_MAX npb_None_t
#define _npb_TypeEnum_ARRAYSIZE ((npb_TypeEnum)(npb_None_t+1))
#define npb_TypeEnum_None_t npb_None_t


#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
