/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_NPB_TYPEENUM_PB_H_INCLUDED
#define PB_NPB_TYPEENUM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _npb_TypeEnum { 
    npb_Unknown_t = 0, 
    /* POD */
    npb_Double_t = 1, 
    npb_Float_t = 2, 
    npb_Int32_t = 3, 
    npb_Int64_t = 4, 
    npb_UInt32_t = 5, 
    npb_UInt64_t = 6, 
    npb_Bool_t = 7, 
    /* Strings */
    npb_Bytes_t = 8, 
    npb_String_t = 9, 
    /* Vectors */
    npb_Vector2d_t = 20, 
    npb_Vector2f_t = 21, 
    npb_Vector2i_t = 22, 
    npb_Vector2c_t = 23, 
    npb_Vector3d_t = 24, 
    npb_Vector3f_t = 25, 
    npb_Vector3i_t = 26, 
    npb_Vector3c_t = 27, 
    npb_Vector4d_t = 28, 
    npb_Vector4f_t = 29, 
    npb_Vector4i_t = 30, 
    npb_Vector4c_t = 31, 
    npb_Vector6d_t = 32, 
    npb_Vector6f_t = 33, 
    npb_Vector6i_t = 34, 
    npb_Vector6c_t = 35, 
    npb_Vector12d_t = 36, 
    npb_Vector12f_t = 37, 
    npb_Vector12i_t = 38, 
    npb_Vector12c_t = 39, 
    npb_Vector16d_t = 40, 
    npb_Vector16f_t = 41, 
    npb_Vector16i_t = 42, 
    npb_Vector16c_t = 43, 
    npb_Vector32d_t = 44, 
    npb_Vector32f_t = 45, 
    npb_Vector32i_t = 46, 
    npb_Vector32c_t = 47, 
    npb_Vector64d_t = 48, 
    npb_Vector64f_t = 49, 
    npb_Vector64i_t = 50, 
    npb_Vector64c_t = 51 
} npb_TypeEnum;

/* Helper constants for enums */
#define _npb_TypeEnum_MIN npb_Unknown_t
#define _npb_TypeEnum_MAX npb_Vector64c_t
#define _npb_TypeEnum_ARRAYSIZE ((npb_TypeEnum)(npb_Vector64c_t+1))
#define npb_TypeEnum_Unknown_t npb_Unknown_t
#define npb_TypeEnum_Double_t npb_Double_t
#define npb_TypeEnum_Float_t npb_Float_t
#define npb_TypeEnum_Int32_t npb_Int32_t
#define npb_TypeEnum_Int64_t npb_Int64_t
#define npb_TypeEnum_UInt32_t npb_UInt32_t
#define npb_TypeEnum_UInt64_t npb_UInt64_t
#define npb_TypeEnum_Bool_t npb_Bool_t
#define npb_TypeEnum_Bytes_t npb_Bytes_t
#define npb_TypeEnum_String_t npb_String_t
#define npb_TypeEnum_Vector2d_t npb_Vector2d_t
#define npb_TypeEnum_Vector2f_t npb_Vector2f_t
#define npb_TypeEnum_Vector2i_t npb_Vector2i_t
#define npb_TypeEnum_Vector2c_t npb_Vector2c_t
#define npb_TypeEnum_Vector3d_t npb_Vector3d_t
#define npb_TypeEnum_Vector3f_t npb_Vector3f_t
#define npb_TypeEnum_Vector3i_t npb_Vector3i_t
#define npb_TypeEnum_Vector3c_t npb_Vector3c_t
#define npb_TypeEnum_Vector4d_t npb_Vector4d_t
#define npb_TypeEnum_Vector4f_t npb_Vector4f_t
#define npb_TypeEnum_Vector4i_t npb_Vector4i_t
#define npb_TypeEnum_Vector4c_t npb_Vector4c_t
#define npb_TypeEnum_Vector6d_t npb_Vector6d_t
#define npb_TypeEnum_Vector6f_t npb_Vector6f_t
#define npb_TypeEnum_Vector6i_t npb_Vector6i_t
#define npb_TypeEnum_Vector6c_t npb_Vector6c_t
#define npb_TypeEnum_Vector12d_t npb_Vector12d_t
#define npb_TypeEnum_Vector12f_t npb_Vector12f_t
#define npb_TypeEnum_Vector12i_t npb_Vector12i_t
#define npb_TypeEnum_Vector12c_t npb_Vector12c_t
#define npb_TypeEnum_Vector16d_t npb_Vector16d_t
#define npb_TypeEnum_Vector16f_t npb_Vector16f_t
#define npb_TypeEnum_Vector16i_t npb_Vector16i_t
#define npb_TypeEnum_Vector16c_t npb_Vector16c_t
#define npb_TypeEnum_Vector32d_t npb_Vector32d_t
#define npb_TypeEnum_Vector32f_t npb_Vector32f_t
#define npb_TypeEnum_Vector32i_t npb_Vector32i_t
#define npb_TypeEnum_Vector32c_t npb_Vector32c_t
#define npb_TypeEnum_Vector64d_t npb_Vector64d_t
#define npb_TypeEnum_Vector64f_t npb_Vector64f_t
#define npb_TypeEnum_Vector64i_t npb_Vector64i_t
#define npb_TypeEnum_Vector64c_t npb_Vector64c_t


#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
