/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_LS_PROTO_LS_PROTO_ARRAY_PB_H_INCLUDED
#define PB_LS_PROTO_LS_PROTO_ARRAY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ls_proto_ArrayBool { 
    int32_t size; 
    pb_callback_t values; 
} ls_proto_ArrayBool;

typedef struct _ls_proto_ArrayBytes { 
    int32_t size; 
    pb_callback_t values; 
} ls_proto_ArrayBytes;

typedef struct _ls_proto_ArrayDouble { 
    int32_t size; 
    pb_callback_t values; 
} ls_proto_ArrayDouble;

typedef struct _ls_proto_ArrayFloat { 
    int32_t size; 
    pb_callback_t values; 
} ls_proto_ArrayFloat;

typedef struct _ls_proto_ArrayInt32 { 
    int32_t size; 
    pb_callback_t values; 
} ls_proto_ArrayInt32;

typedef struct _ls_proto_ArrayInt64 { 
    int32_t size; 
    pb_callback_t values; 
} ls_proto_ArrayInt64;

typedef struct _ls_proto_ArrayUInt32 { 
    int32_t size; 
    pb_callback_t values; 
} ls_proto_ArrayUInt32;

typedef struct _ls_proto_ArrayUInt64 { 
    int32_t size; 
    pb_callback_t values; 
} ls_proto_ArrayUInt64;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ls_proto_ArrayBool_init_default          {0, {{NULL}, NULL}}
#define ls_proto_ArrayBytes_init_default         {0, {{NULL}, NULL}}
#define ls_proto_ArrayDouble_init_default        {0, {{NULL}, NULL}}
#define ls_proto_ArrayFloat_init_default         {0, {{NULL}, NULL}}
#define ls_proto_ArrayInt32_init_default         {0, {{NULL}, NULL}}
#define ls_proto_ArrayUInt32_init_default        {0, {{NULL}, NULL}}
#define ls_proto_ArrayInt64_init_default         {0, {{NULL}, NULL}}
#define ls_proto_ArrayUInt64_init_default        {0, {{NULL}, NULL}}
#define ls_proto_ArrayBool_init_zero             {0, {{NULL}, NULL}}
#define ls_proto_ArrayBytes_init_zero            {0, {{NULL}, NULL}}
#define ls_proto_ArrayDouble_init_zero           {0, {{NULL}, NULL}}
#define ls_proto_ArrayFloat_init_zero            {0, {{NULL}, NULL}}
#define ls_proto_ArrayInt32_init_zero            {0, {{NULL}, NULL}}
#define ls_proto_ArrayUInt32_init_zero           {0, {{NULL}, NULL}}
#define ls_proto_ArrayInt64_init_zero            {0, {{NULL}, NULL}}
#define ls_proto_ArrayUInt64_init_zero           {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define ls_proto_ArrayBool_size_tag              1
#define ls_proto_ArrayBool_values_tag            2
#define ls_proto_ArrayBytes_size_tag             1
#define ls_proto_ArrayBytes_values_tag           2
#define ls_proto_ArrayDouble_size_tag            1
#define ls_proto_ArrayDouble_values_tag          2
#define ls_proto_ArrayFloat_size_tag             1
#define ls_proto_ArrayFloat_values_tag           2
#define ls_proto_ArrayInt32_size_tag             1
#define ls_proto_ArrayInt32_values_tag           2
#define ls_proto_ArrayInt64_size_tag             1
#define ls_proto_ArrayInt64_values_tag           2
#define ls_proto_ArrayUInt32_size_tag            1
#define ls_proto_ArrayUInt32_values_tag          2
#define ls_proto_ArrayUInt64_size_tag            1
#define ls_proto_ArrayUInt64_values_tag          2

/* Struct field encoding specification for nanopb */
#define ls_proto_ArrayBool_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    size,              1) \
X(a, CALLBACK, REPEATED, BOOL,     values,            2)
#define ls_proto_ArrayBool_CALLBACK pb_default_field_callback
#define ls_proto_ArrayBool_DEFAULT NULL

#define ls_proto_ArrayBytes_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    size,              1) \
X(a, CALLBACK, REPEATED, BYTES,    values,            2)
#define ls_proto_ArrayBytes_CALLBACK pb_default_field_callback
#define ls_proto_ArrayBytes_DEFAULT NULL

#define ls_proto_ArrayDouble_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    size,              1) \
X(a, CALLBACK, REPEATED, DOUBLE,   values,            2)
#define ls_proto_ArrayDouble_CALLBACK pb_default_field_callback
#define ls_proto_ArrayDouble_DEFAULT NULL

#define ls_proto_ArrayFloat_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    size,              1) \
X(a, CALLBACK, REPEATED, FLOAT,    values,            2)
#define ls_proto_ArrayFloat_CALLBACK pb_default_field_callback
#define ls_proto_ArrayFloat_DEFAULT NULL

#define ls_proto_ArrayInt32_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    size,              1) \
X(a, CALLBACK, REPEATED, INT32,    values,            2)
#define ls_proto_ArrayInt32_CALLBACK pb_default_field_callback
#define ls_proto_ArrayInt32_DEFAULT NULL

#define ls_proto_ArrayUInt32_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    size,              1) \
X(a, CALLBACK, REPEATED, UINT32,   values,            2)
#define ls_proto_ArrayUInt32_CALLBACK pb_default_field_callback
#define ls_proto_ArrayUInt32_DEFAULT NULL

#define ls_proto_ArrayInt64_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    size,              1) \
X(a, CALLBACK, REPEATED, INT64,    values,            2)
#define ls_proto_ArrayInt64_CALLBACK pb_default_field_callback
#define ls_proto_ArrayInt64_DEFAULT NULL

#define ls_proto_ArrayUInt64_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    size,              1) \
X(a, CALLBACK, REPEATED, UINT64,   values,            2)
#define ls_proto_ArrayUInt64_CALLBACK pb_default_field_callback
#define ls_proto_ArrayUInt64_DEFAULT NULL

extern const pb_msgdesc_t ls_proto_ArrayBool_msg;
extern const pb_msgdesc_t ls_proto_ArrayBytes_msg;
extern const pb_msgdesc_t ls_proto_ArrayDouble_msg;
extern const pb_msgdesc_t ls_proto_ArrayFloat_msg;
extern const pb_msgdesc_t ls_proto_ArrayInt32_msg;
extern const pb_msgdesc_t ls_proto_ArrayUInt32_msg;
extern const pb_msgdesc_t ls_proto_ArrayInt64_msg;
extern const pb_msgdesc_t ls_proto_ArrayUInt64_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ls_proto_ArrayBool_fields &ls_proto_ArrayBool_msg
#define ls_proto_ArrayBytes_fields &ls_proto_ArrayBytes_msg
#define ls_proto_ArrayDouble_fields &ls_proto_ArrayDouble_msg
#define ls_proto_ArrayFloat_fields &ls_proto_ArrayFloat_msg
#define ls_proto_ArrayInt32_fields &ls_proto_ArrayInt32_msg
#define ls_proto_ArrayUInt32_fields &ls_proto_ArrayUInt32_msg
#define ls_proto_ArrayInt64_fields &ls_proto_ArrayInt64_msg
#define ls_proto_ArrayUInt64_fields &ls_proto_ArrayUInt64_msg

/* Maximum encoded size of messages (where known) */
/* ls_proto_ArrayBool_size depends on runtime parameters */
/* ls_proto_ArrayBytes_size depends on runtime parameters */
/* ls_proto_ArrayDouble_size depends on runtime parameters */
/* ls_proto_ArrayFloat_size depends on runtime parameters */
/* ls_proto_ArrayInt32_size depends on runtime parameters */
/* ls_proto_ArrayUInt32_size depends on runtime parameters */
/* ls_proto_ArrayInt64_size depends on runtime parameters */
/* ls_proto_ArrayUInt64_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
