/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_LS_PROTO_LS_PROTO_ENCRYPTION_PB_H_INCLUDED
#define PB_LS_PROTO_LS_PROTO_ENCRYPTION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _ls_proto_Encryption { 
    ls_proto_Encryption_ed25519 = 0 
} ls_proto_Encryption;

/* Helper constants for enums */
#define _ls_proto_Encryption_MIN ls_proto_Encryption_ed25519
#define _ls_proto_Encryption_MAX ls_proto_Encryption_ed25519
#define _ls_proto_Encryption_ARRAYSIZE ((ls_proto_Encryption)(ls_proto_Encryption_ed25519+1))


#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
