/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_LS_PROTO_LS_PROTO_MATRIX_PB_H_INCLUDED
#define PB_LS_PROTO_LS_PROTO_MATRIX_PB_H_INCLUDED
#include <pb.h>
#include "ls.proto.types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _ls_proto_MatrixOrdering { 
    ls_proto_MatrixOrdering_colMajor = 0, 
    ls_proto_MatrixOrdering_rowMajor = 1 
} ls_proto_MatrixOrdering;

/* Struct definitions */
typedef struct _ls_proto_MatrixHerald { 
    ls_proto_Type type; 
    int32_t rows; 
    int32_t cols; 
    bool has_ordering;
    ls_proto_MatrixOrdering ordering; 
} ls_proto_MatrixHerald;


/* Helper constants for enums */
#define _ls_proto_MatrixOrdering_MIN ls_proto_MatrixOrdering_colMajor
#define _ls_proto_MatrixOrdering_MAX ls_proto_MatrixOrdering_rowMajor
#define _ls_proto_MatrixOrdering_ARRAYSIZE ((ls_proto_MatrixOrdering)(ls_proto_MatrixOrdering_rowMajor+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ls_proto_MatrixHerald_init_default       {_ls_proto_Type_MIN, 0, 0, false, _ls_proto_MatrixOrdering_MIN}
#define ls_proto_MatrixHerald_init_zero          {_ls_proto_Type_MIN, 0, 0, false, _ls_proto_MatrixOrdering_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define ls_proto_MatrixHerald_type_tag           1
#define ls_proto_MatrixHerald_rows_tag           2
#define ls_proto_MatrixHerald_cols_tag           3
#define ls_proto_MatrixHerald_ordering_tag       4

/* Struct field encoding specification for nanopb */
#define ls_proto_MatrixHerald_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    type,              1) \
X(a, STATIC,   REQUIRED, INT32,    rows,              2) \
X(a, STATIC,   REQUIRED, INT32,    cols,              3) \
X(a, STATIC,   OPTIONAL, UENUM,    ordering,          4)
#define ls_proto_MatrixHerald_CALLBACK NULL
#define ls_proto_MatrixHerald_DEFAULT NULL

extern const pb_msgdesc_t ls_proto_MatrixHerald_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ls_proto_MatrixHerald_fields &ls_proto_MatrixHerald_msg

/* Maximum encoded size of messages (where known) */
#define ls_proto_MatrixHerald_size               26

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
