/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_LS_PROTO_LS_PROTO_TYPES_PB_H_INCLUDED
#define PB_LS_PROTO_LS_PROTO_TYPES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _ls_proto_Type { 
    ls_proto_Type_unknown_t = 0, 
    ls_proto_Type_bool_t = 1, 
    ls_proto_Type_int_t = 2, 
    ls_proto_Type_int32_t = 3, 
    ls_proto_Type_uint32_t = 4, 
    ls_proto_Type_int64_t = 5, 
    ls_proto_Type_uint64_t = 6, 
    ls_proto_Type_double_t = 7, 
    ls_proto_Type_float_t = 8, 
    ls_proto_Type_char_t = 9, 
    ls_proto_Type_matrix_t = 10, 
    ls_proto_Type_vector_t = 11 
} ls_proto_Type;

/* Helper constants for enums */
#define _ls_proto_Type_MIN ls_proto_Type_unknown_t
#define _ls_proto_Type_MAX ls_proto_Type_vector_t
#define _ls_proto_Type_ARRAYSIZE ((ls_proto_Type)(ls_proto_Type_vector_t+1))


#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
