/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_LS_PROTO_LS_PROTO_SIGNATURE_PB_H_INCLUDED
#define PB_LS_PROTO_LS_PROTO_SIGNATURE_PB_H_INCLUDED
#include <pb.h>
#include "ls.proto.encryption.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ls_proto_Signature { 
    bool has_enc;
    ls_proto_Encryption enc; 
    bool has_sign0;
    uint64_t sign0; 
    bool has_sign1;
    uint64_t sign1; 
    bool has_sign2;
    uint64_t sign2; 
    bool has_sign3;
    uint64_t sign3; 
    bool has_sign4;
    uint64_t sign4; 
    bool has_sign5;
    uint64_t sign5; 
    bool has_sign6;
    uint64_t sign6; 
    bool has_sign7;
    uint64_t sign7; 
    bool has_pk0;
    uint64_t pk0; 
    bool has_pk1;
    uint64_t pk1; 
    bool has_pk2;
    uint64_t pk2; 
    bool has_pk3;
    uint64_t pk3; 
} ls_proto_Signature;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ls_proto_Signature_init_default          {false, _ls_proto_Encryption_MIN, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define ls_proto_Signature_init_zero             {false, _ls_proto_Encryption_MIN, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ls_proto_Signature_enc_tag               1
#define ls_proto_Signature_sign0_tag             2
#define ls_proto_Signature_sign1_tag             3
#define ls_proto_Signature_sign2_tag             4
#define ls_proto_Signature_sign3_tag             5
#define ls_proto_Signature_sign4_tag             6
#define ls_proto_Signature_sign5_tag             7
#define ls_proto_Signature_sign6_tag             8
#define ls_proto_Signature_sign7_tag             9
#define ls_proto_Signature_pk0_tag               10
#define ls_proto_Signature_pk1_tag               11
#define ls_proto_Signature_pk2_tag               12
#define ls_proto_Signature_pk3_tag               13

/* Struct field encoding specification for nanopb */
#define ls_proto_Signature_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    enc,               1) \
X(a, STATIC,   OPTIONAL, FIXED64,  sign0,             2) \
X(a, STATIC,   OPTIONAL, FIXED64,  sign1,             3) \
X(a, STATIC,   OPTIONAL, FIXED64,  sign2,             4) \
X(a, STATIC,   OPTIONAL, FIXED64,  sign3,             5) \
X(a, STATIC,   OPTIONAL, FIXED64,  sign4,             6) \
X(a, STATIC,   OPTIONAL, FIXED64,  sign5,             7) \
X(a, STATIC,   OPTIONAL, FIXED64,  sign6,             8) \
X(a, STATIC,   OPTIONAL, FIXED64,  sign7,             9) \
X(a, STATIC,   OPTIONAL, FIXED64,  pk0,              10) \
X(a, STATIC,   OPTIONAL, FIXED64,  pk1,              11) \
X(a, STATIC,   OPTIONAL, FIXED64,  pk2,              12) \
X(a, STATIC,   OPTIONAL, FIXED64,  pk3,              13)
#define ls_proto_Signature_CALLBACK NULL
#define ls_proto_Signature_DEFAULT NULL

extern const pb_msgdesc_t ls_proto_Signature_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ls_proto_Signature_fields &ls_proto_Signature_msg

/* Maximum encoded size of messages (where known) */
#define ls_proto_Signature_size                  110

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
