/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "ls.proto.array.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ls_proto_ArrayBool, ls_proto_ArrayBool, AUTO)


PB_BIND(ls_proto_ArrayBytes, ls_proto_ArrayBytes, AUTO)


PB_BIND(ls_proto_ArrayDouble, ls_proto_ArrayDouble, AUTO)


PB_BIND(ls_proto_ArrayFloat, ls_proto_ArrayFloat, AUTO)


PB_BIND(ls_proto_ArrayInt32, ls_proto_ArrayInt32, AUTO)


PB_BIND(ls_proto_ArrayUInt32, ls_proto_ArrayUInt32, AUTO)


PB_BIND(ls_proto_ArrayInt64, ls_proto_ArrayInt64, AUTO)


PB_BIND(ls_proto_ArrayUInt64, ls_proto_ArrayUInt64, AUTO)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

