name: Doxygen deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install doxygen
        run: |
          sudo apt-add-repository universe
          sudo apt-get update
          sudo apt-get install doxygen graphviz

      - name: Build documentation
        run: |
          cd doc
          doxygen Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: docs-cpp
          publish_dir: ./doc/out/html
          cname: docs.ldstr.dev